file:
  server:
    host: 127.0.0.1

spring:
  application:
    name: chama-polls

#  datasource:
#    username: backend
#    password: Vicoba.22
#    url: jdbc:postgresql://192.168.20.41:5432/chamadb2


  datasource:
    password: Amosmark
    url: jdbc:postgresql://localhost:5432/chamadb
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

    servlet:
      multipart:
        max-file-size: 10000KB
        max-request-size: 10000KB

    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.20.66:9092
          auto-create-topics: true

  redis:
    host: 192.168.20.66
    port: 6379

app-configs:
  app-signature: cGQNrYD7Sl5
  online-checkout: https://testgateway.ekenya.co.ke:8443/ServiceLayer/onlinecheckout/request
  sms-url: https://testgateway.ekenya.co.ke:8443/ServiceLayer/pgsms/send
  b2c-url: https://testgateway.ekenya.co.ke:8443/ServiceLayer/request/postRequest
  online-query: https://testgateway.ekenya.co.ke:8443/ServiceLayer/onlinecheckout/query
  b2c-online-query: https://testgateway.ekenya.co.ke:8443/ServiceLayer/transaction/query
  countries-directory: configs/country-codes.json
  regions-directory: configs/senegal-regions.json
  nationality-directory: configs/nationality.json
  jwt-name: chamajwtsec
  sms-url-dev: https://testgateway.ekenya.co.ke:8443/ServiceLayer/pgsms/send
  sms-url-prod: https://eclecticsgateway.ekenya.co.ke:8095/ServiceLayer/pgsms/send
  online-checkout-prod: https://eclecticsgateway.ekenya.co.ke:8095/ServiceLayer/onlinecheckout/request
  online-query-prod: https://eclecticsgateway.ekenya.co.ke:8095/ServiceLayer/onlinecheckout/query
  b2c-url-dev: https://testgateway.ekenya.co.ke:8443/ServiceLayer/request/postRequest
  b2c-url-prod: https://eclecticsgateway.ekenya.co.ke:8095/ServiceLayer/request/postRequest
  b2c-url-query-prod: https://eclecticsgateway.ekenya.co.ke:8095/ServiceLayer/transaction/query
  esb-url: http://10.20.2.12:8082/api/EsbPublicService
  AccountsConfig-directory: configs/AccountsConfig.json
  walletServicesWrapper-directory: configs/walletServicesWrapper.json
  sms-from: FEPGROUP
  pg-client-username: chama
  pg-client-id: 5141
  pg-service-id: 5067
  pg-service-b2c-id: 6125
  pg-client-name: ECLECTICS
  pg-client-password: 3b9b2656eba1b600277c11b8ec7bd692a574f1f4d888e444bc138647458f70f74fab69132498d2074980d4575bbf54ac608aa9df0dba110c834511c218647657

payments:
  pg_username: chama
  pg_password: 3b9b2656eba1b600277c11b8ec7bd692a574f1f4d888e444bc138647458f70f74fab69132498d2074980d4575bbf54ac608aa9df0dba110c834511c218647657
  pg_client_id: 5141
  pg_service_id: 5067


wallet:
  gl_account_number: TA2458649000001
  gl_phonenumber: 783490023

logging:
  file:
    name: logs/application.log
  level:
    org.apache: OFF
    kafka: OFF

app:
  security:
    jwt:
      keystore-name: authorization.p12
      keystore-password: RSwr$%@8L?
      key-alias: eclectics-auth

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.20.66:8761/eureka}
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost