spring:
  profiles:
#    active: vicoba
    active: dev

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

server:
#  port: ${AUTH_PORT}
  port: 8772

logging:
  file:
    name: chama-authorization-logs
    path: logs

