server:
  port: ${GATEWAY_PORT}
  ssl:
    enabled: true
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store: ${SSL_KEYSTORE}
    key-store-type: ${SSL_KEYSTORE_TYPE}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: chama-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: 192.168.20.32:9092

ip:
  whitelist: ${IP_WHITELIST}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_IP_ADDRESS}
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: ${HOST_NAME}
    prefer-ip-address: true

auth:
  server:
    url: http://192.168.20.32:8772/
    basic: ${AUTH_SERVER_BASIC_CREDENTIALS}