server:
  port: ${USSD_GATEWAY_PORT}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: chama-ussd-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

ip:
  whitelist: ${USSD_IP_WHITELIST}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_IP_ADDRESS}
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: ${HOST_NAME}
    prefer-ip-address: true

auth:
  server:
    url: ${AUTH_SERVER_URL}
    basic: ${AUTH_SERVER_BASIC_CREDENTIALS}