-- auto-generated definition
create table oauth_access_token
(
    token_id          varchar(255),
    token             bytea,
    authentication_id varchar(255) not null
        primary key,
    user_name         varchar(255),
    client_id         varchar(255),
    authentication    bytea,
    refresh_token     varchar(255)
);
create table if not exists oauth_client_details
(
    client_id               varchar(64) not null
        primary key,
    access_token_validity   integer,
    additional_information  varchar(255),
    authorities             varchar(255),
    authorized_grant_types  varchar(255),
    autoapprove             varchar(255),
    client_secret           varchar(255),
    refresh_token_validity  integer,
    resource_ids            varchar(255),
    scope                   varchar(255),
    web_server_redirect_uri varchar(255)
);
-- auto-generated definition
create table oauth_refresh_token
(
    token_id       varchar(255),
    token          bytea,
    authentication bytea
);
-- Add Oauth Details
INSERT INTO public.oauth_client_details (client_id, access_token_validity, additional_information, authorities, authorized_grant_types, autoapprove, client_secret, refresh_token_validity, resource_ids, scope, web_server_redirect_uri) VALUES ('esb_5_1_clientid', 3600, null, null, 'password,authorization_code,refresh_token,client_credentials', 'true', '$2a$10$ygBh9zSTH4x0GFUCFIsfW.tKmbdgUxBgL/HlL8fPgtLmOmymKm0fy', 900, 'esb_5_1', 'read,write', null);
INSERT INTO public.oauth_client_details (client_id, access_token_validity, additional_information, authorities, authorized_grant_types, autoapprove, client_secret, refresh_token_validity, resource_ids, scope, web_server_redirect_uri) VALUES ('finmanager_clientid_130', 3600, null, null, 'password,authorization_code,refresh_token,client_credentials', 'true', '$2a$10$blmViDr01jgrqfPEbgZ0DO5G4/0eFDy7hQ4LdtP2RFISzij4LpDTu', 900, 'finmanager', 'read,write', null);
INSERT INTO public.oauth_client_details (client_id, access_token_validity, additional_information, authorities, authorized_grant_types, autoapprove, client_secret, refresh_token_validity, resource_ids, scope, web_server_redirect_uri) VALUES ('chama_portal', 3600, null, null, 'password,authorization_code,refresh_token,client_credentials', 'true', '$2a$10$PRBU2uE4ASHb82Wk/sFa2u926Sk9QgMUGnBbQnE1Xn5QL0wyjMO/G', 4800, 'chama', 'read,write', null);
INSERT INTO public.oauth_client_details (client_id, access_token_validity, additional_information, authorities, authorized_grant_types, autoapprove, client_secret, refresh_token_validity, resource_ids, scope, web_server_redirect_uri) VALUES ('chama_clientid', 3600, null, null, 'password,authorization_code,refresh_token,client_credentials', 'true', '$2a$10$dpBu3VRo9.EWKulX53NsSOv8OWSjyXC1jbiWYbszKfAlBsadqQVjS', 300, 'chama', 'read,write', null);

-- Add Account Type Data
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (1, null, '2020-01-31 13:29:25.000000', null, null, false, '[]', 'Wallet Account', 'WA');
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (2, null, '2020-01-31 13:29:25.000000', null, null, false, '["account_number", "branch", "bank_name"]', 'Bank Account', 'BA');
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (3, null, '2020-01-31 13:29:25.000000', null, null, false, '["account_number"]', 'Mobile Money Account', 'MMA');
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (4, null, '2020-01-31 13:29:25.000000', null, null, false, '["account_number", "branch", "sacco_name"]', 'Sacco Account', 'SA');
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (5, null, '2020-01-31 13:29:25.000000', null, null, false, '["account_number"]', 'Petty Cash Account', 'PCA');
INSERT INTO public.account_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, account_fields, account_name, account_prefix) VALUES (7, null, '2020-04-08 14:53:27.000000', null, null, false, '["description", "managedby"]', 'Investment', 'IN');
-- Add Amount Types Data
INSERT INTO public.amount_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (1, null, '2020-03-23 14:35:22.000000', null, null, false, 'fixed amount');
INSERT INTO public.amount_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (2, null, '2020-03-23 14:44:35.000000', null, null, false, 'any amount');
INSERT INTO public.amount_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (3, null, '2021-03-29 09:01:16.000000', null, null, false, 'Non-fixed Amount');
INSERT INTO public.amount_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (4, null, '2021-04-15 11:57:39.000000', null, null, false, 'Flexible amount');
-- Add Contribution Types Data
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (1, null, '2020-03-23 12:44:06.000000', null, null, false, 'recurring contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (2, null, '2020-03-23 14:49:25.000000', null, null, false, 'one time contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (3, null, '2021-03-29 08:58:13.000000', null, null, false, 'Bi-Weekly Contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (4, null, '2021-04-15 12:01:14.000000', null, null, false, 'Monthly Contribution');
-- Add Group Category Data
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (1, null, '2020-03-23 12:44:06.000000', null, null, false, 'recurring contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (2, null, '2020-03-23 14:49:25.000000', null, null, false, 'one time contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (3, null, '2021-03-29 08:58:13.000000', null, null, false, 'Bi-Weekly Contribution');
INSERT INTO public.contribution_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (4, null, '2021-04-15 12:01:14.000000', null, null, false, 'Monthly Contribution');
-- Add Group Titles Data
INSERT INTO public.group_titles_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, permissions, titlename) VALUES (5, 'ADMIN', '2022-06-16 16:51:12.000000', 'ADMIN', '2022-06-16 16:51:24.000000', false, '{loans=[cancreate, candelete, canedit, canview], invites=[cancreate, candelete, canedit, canview], members=[cancreate, candelete, canedit, canview], withdraw=[cancreate, candelete, canedit, canview], documents=[cancreate, candelete, canedit, canview], finepayment=[cancreate, candelete, canedit, canview], loanpayment=[cancreate, candelete, canedit, canview], loanproduct=[cancreate, candelete, canedit, canview], groupaccount=[cancreate, candelete, canedit, canview], groupdetails=[cancreate, candelete, canedit, canview], loanapproval=[cancreate, candelete, canedit, canview], loanapplication=[cancreate, candelete, canedit, canview], paymentapproval=[cancreate, candelete, canedit, canview], grouptransactions=[cancreate, candelete, canedit, canview], withdrawalapproval=[cancreate, candelete, canedit, canview], polls=[cancreate, canedit, canview, candelete], contributionpayment=[cancreate, canedit, canview]}', 'Secretary');
INSERT INTO public.group_titles_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, permissions, titlename) VALUES (4, 'ADMIN', '2022-06-16 16:51:11.000000', 'ADMIN', '2022-06-16 16:51:24.000000', false, '{loans=[cancreate, candelete, canedit, canview], invites=[cancreate, candelete, canedit, canview], members=[cancreate, candelete, canedit, canview], withdraw=[cancreate, candelete, canedit, canview], documents=[cancreate, candelete, canedit, canview], finepayment=[cancreate, candelete, canedit, canview], loanpayment=[cancreate, candelete, canedit, canview], loanproduct=[cancreate, candelete, canedit, canview], groupaccount=[cancreate, candelete, canedit, canview], groupdetails=[cancreate, candelete, canedit, canview], loanapproval=[cancreate, candelete, canedit, canview], loanapplication=[cancreate, candelete, canedit, canview], paymentapproval=[cancreate, candelete, canedit, canview], grouptransactions=[cancreate, candelete, canedit, canview], withdrawalapproval=[cancreate, candelete, canedit, canview], polls=[cancreate, canedit, canview, candelete], contributionpayment=[cancreate, canedit, canview]}', 'Treasurer');
INSERT INTO public.group_titles_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, permissions, titlename) VALUES (3, 'ADMIN', '2022-06-16 16:51:10.000000', 'ADMIN', '2022-06-16 16:51:23.000000', false, '{loans=[cancreate, candelete, canedit, canview], invites=[cancreate, candelete, canedit, canview], members=[cancreate, candelete, canedit, canview], withdraw=[cancreate, candelete, canedit, canview], documents=[cancreate, candelete, canedit, canview], finepayment=[cancreate, candelete, canedit, canview], loanpayment=[cancreate, candelete, canedit, canview], loanproduct=[cancreate, candelete, canedit, canview], groupaccount=[cancreate, candelete, canedit, canview], groupdetails=[cancreate, candelete, canedit, canview], loanapproval=[cancreate, candelete, canedit, canview], loanapplication=[cancreate, candelete, canedit, canview], paymentapproval=[cancreate, candelete, canedit, canview], grouptransactions=[cancreate, candelete, canedit, canview], withdrawalapproval=[cancreate, candelete, canedit, canview], polls=[cancreate, canedit, canview, candelete], contributionpayment=[cancreate, canedit, canview]}', 'Chairperson');
INSERT INTO public.group_titles_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, permissions, titlename) VALUES (2, 'ADMIN', '2022-06-16 16:51:10.000000', 'ADMIN', '2022-06-16 16:51:22.000000', false, '{loans=[cancreate, candelete, canedit, canview], invites=[cancreate, candelete, canedit, canview], members=[cancreate, candelete, canedit, canview], withdraw=[cancreate, candelete, canedit, canview], documents=[cancreate, candelete, canedit, canview], finepayment=[cancreate, candelete, canedit, canview], loanpayment=[cancreate, candelete, canedit, canview], loanproduct=[cancreate, candelete, canedit, canview], groupaccount=[cancreate, candelete, canedit, canview], groupdetails=[cancreate, candelete, canedit, canview], loanapproval=[cancreate, candelete, canedit, canview], loanapplication=[cancreate, candelete, canedit, canview], paymentapproval=[cancreate, candelete, canedit, canview], grouptransactions=[cancreate, candelete, canedit, canview], withdrawalapproval=[cancreate, candelete, canedit, canview], polls=[cancreate, canedit, canview, candelete], contributionpayment=[cancreate, canedit, canview]}', 'Creator');
INSERT INTO public.group_titles_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, permissions, titlename) VALUES (1, 'ADMIN', '2022-06-16 16:51:06.000000', 'ADMIN', '2022-06-16 16:51:20.000000', false, '{loans=[cancreate, candelete, canedit, canview], invites=[cancreate, candelete, canedit, canview], members=[cancreate, candelete, canedit, canview], withdraw=[cancreate, candelete, canedit, canview], documents=[cancreate, candelete, canedit, canview], finepayment=[cancreate, candelete, canedit, canview], loanpayment=[cancreate, candelete, canedit, canview], loanproduct=[cancreate, candelete, canedit, canview], groupaccount=[cancreate, candelete, canedit, canview], groupdetails=[cancreate, candelete, canedit, canview], loanapproval=[cancreate, candelete, canedit, canview], loanapplication=[cancreate, candelete, canedit, canview], paymentapproval=[cancreate, candelete, canedit, canview], grouptransactions=[cancreate, candelete, canedit, canview], withdrawalapproval=[cancreate, candelete, canedit, canview], polls=[cancreate, canedit, canview, candelete], contributionpayment=[cancreate, canedit, canview]}', 'Member');
-- Add Message Templates Data
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (54, '2021-10-13 12:35:42.000000', false, 'English', '%s poll has been deleted by %s.', 'delete_poll');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (168, '2021-10-13 15:39:39.000000', false, 'English', ' %s has invited member with phone number %s to group %s.', 'member_invited');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (171, '2021-10-13 12:35:42.000000', false, 'English', 'Poll for group %s has began. The poll is open from %s to %s.', 'poll_started');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (14, '2021-04-15 11:31:53.000000', false, 'English', 'Withdrawal Notification', 'withdrawal_notification_subject');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (15, '2021-06-22 10:42:39.000000', false, 'English', 'Click on the provided link to activate your account and login', 'new_account_activation_email');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (22, '2021-10-13 15:06:47.000000', false, 'English', 'Dear %s, your request to leave group %s has been approved. You are no longer a member of this group.', 'leave_group_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (23, '2021-10-13 15:20:44.000000', false, 'English', 'Dear %s, your request to leave group %s has been declined. Kindly contact the group''s management/committee.', 'leave_group_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (26, '2021-10-14 09:57:12.000000', false, 'English', '<#> Dear %s, use  %s to verify your device. %s', 'device_verification');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (27, '2021-10-14 11:00:05.000000', false, 'English', '<#> Dear %s, use %s as your pin to login to Chama application. %s', 'first_time_login');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (153, '2021-10-13 12:35:42.000000', false, 'English', 'Kura ya %s imefutwa na %s.', 'delete_poll');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (18, '2021-10-13 12:35:42.000000', false, 'English', 'Dear %s, your group contribution payment of Tsh %s, has been received.  ', 'contribution_payment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (29, '2021-10-20 11:28:12.000000', false, 'English', 'Dear %s, your withdrawal request of Tsh %s , has been approved. The money will be disbursed to your account.', 'withdrawal_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (17, '2021-10-13 12:27:03.000000', false, 'English', 'Dear %s, your group contribution payment of Tsh %s, could not be completed.  ', 'contribution_payment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (30, '2021-10-20 11:30:05.000000', false, 'English', 'Dear %s, your withdrawal request of Tsh %s , has been declined. Kindly contact the group management.', 'withdrawal_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (16, '2021-10-13 11:57:34.000000', false, 'English', 'Dear %s, your penalty payment of Tsh %s could not completed.  ', 'penalty_payment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (20, '2021-10-13 13:48:25.000000', false, 'English', 'Dear %s, your guarantor %s for your loan application of Tsh %s has declined the guarantorship request.', 'guarantor_decline_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (24, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s , your loan of Tsh %s , has been approved. The loan will be disbursed to your account.', 'loan_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (21, '2021-10-13 14:13:44.000000', false, 'English', 'Dear %s, your guarantor %s for your loan application of Tsh %s has accepted the guarantorship request.', 'guarantor_accept_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (25, '2021-10-13 15:54:42.000000', false, 'English', 'Dear %s , your loan of Tsh %s , has been declined. Kindly contact the group management.', 'loan_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (19, '2021-10-13 13:37:57.000000', false, 'English', 'Dear Member, %s has requested you to be guarantor for a loan application of Tsh %s. Kindly login into Chama24 to accept or decline.', 'guarantor_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (50, '2021-10-13 12:35:42.000000', false, 'English', '%s has been elected as the new %s for group %s.  ', 'new_leader_elect');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (31, '2021-10-13 12:35:42.000000', false, 'English', '%s has made a contribution of Tsh. %s successfully to the group %s.  ', 'contribution_payment_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (32, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s , your loan of Tsh. %s , has been disbursed.', 'loan_disburse');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (44, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your request to leave %s has been declined by %s.', 'request_to_leave_decline');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (37, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your withdrawal of Tsh. %s from group %s was not successful.', 'withdrawal_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (33, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, you have a %s upcoming contribution for contribution %s of Tsh. %s.', 'contribution_payment_reminder');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (34, '2021-10-13 15:39:39.000000', false, 'English', '%s, has made a loan repayment for group %s of Tsh. %s.', 'loan_repayment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (35, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your loan repayment of Tsh. %s for group %s was not successful.', 'loan_repayment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (36, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your withdrawal of Tsh. %s from group %s was successful.', 'withdrawal_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (41, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your outstanding contribution payment of Tsh. %s has been paid for group %s ref. %s. New outstanding contribution balance is Tsh %s. ', 'outsanding_contribution_payment');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (39, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, you have been penalised Tsh. %s for group %s contribution ref. number %s. Dial *150*85# to pay. ', 'penalty_created');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (40, '2021-10-13 15:39:39.000000', false, 'English', '%s has attracted a penalty of Tsh. %s for group %s contribution ref. number %s.', 'penalty_created_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (42, '2021-10-13 15:39:39.000000', false, 'English', '%s, has accepted to guarantee %s for their loan application of Tsh. %s', 'guarantor_accept_request_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (43, '2021-10-13 15:39:39.000000', false, 'English', '%s, has declined to guarantee %s for their loan application of Tsh. %s', 'guarantor_decline_request_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (45, '2021-10-13 15:39:39.000000', false, 'English', 'Dear %s, your request to leave %s has been approved by %s.', 'request_to_leave_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (48, '2021-10-13 11:57:34.000000', false, 'English', 'Dear %s, your penalty payment of Tsh %s has been completed.  ', 'penalty_payment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (38, '2021-10-13 15:39:39.000000', false, 'English', '%s, has withdrawn Tsh. %s from group %s.', 'withdrawal_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (47, '2021-10-13 15:39:39.000000', false, 'English', '%s has declined the exit of %s from group %s.', 'request_to_leave_decline_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (46, '2021-10-13 15:39:39.000000', false, 'English', '%s has approved the exit of %s from group %s.', 'request_to_leave_approve_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (49, '2021-10-13 12:35:42.000000', false, 'English', '%s has made a penalty payment of Tsh. %s successfully to the group %s.  ', 'penalty_payment_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (125, '2021-10-13 12:35:42.000000', false, 'Kiswahili', '%s imevutia adhabu ya Tsh. %s kwa kikundi %s rejeleo la mchango. nambari %s.', 'new_leader_elect');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (52, '2021-10-13 12:35:42.000000', false, 'English', 'Your group %s has been deactivated. No transactions will be allowed.', 'group_disabled');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (5, '2020-04-16 10:59:01.000000', false, 'English', 'Use %s to create your password for the Chama Application', 'otpsms');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (8, '2020-04-16 10:59:01.000000', false, 'English', 'You''ve been invited to %s. Download Vicoba app on Google Playstore or iOS Appstore to login/signup and accept invitation.', 'newmember_invitesms');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (170, '2021-10-13 12:35:42.000000', false, 'Kiswahili', '%s amemwalika mwanachama aliye na nambari ya simu %s kwenye kikundi %s.', 'poll_started');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (122, '2021-10-13 14:13:44.000000', false, 'Kiswahili', 'Mpendwa %s, uondoaji wako wa Tsh. %s kutoka kundi %s ilifanikiwa.', 'guarantor_accept_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (141, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s ameunda bidhaa ya mkopo %s kwa ajili ya kikundi %s.', 'withdrawal_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (13, '2021-03-26 14:20:13.000000', false, 'English', 'Welcome %s, achieve your financial goals -save, borrow, invest and grow.', 'newmember_welcomeemail');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (12, '2021-03-26 14:19:06.000000', false, 'English', 'Welcome %s, achieve your financial goals -save, borrow, invest and grow.', 'newmember_inviteemail');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (28, '2021-10-19 23:10:55.000000', false, 'English', 'Dear %s, there was an error transferring %s to your Mpesa account. Please try again later', 'b2c_error');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (169, '2021-10-13 15:39:39.000000', false, 'English', 'Kura ya maoni ya kikundi %s imeanza. Kura ya maoni imefunguliwa kutoka %s hadi %s.', 'member_invited');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (51, '2021-10-13 12:35:42.000000', false, 'English', 'Your group %s has been activated and is now ready to allow transactions.', 'group_enabled');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (155, '2021-10-13 12:35:42.000000', false, 'English', '%s has requested to withdraw Tsh. %s from group %s. ', 'member_withdraw_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (157, '2021-10-13 15:39:39.000000', false, 'English', 'The contribution %s for group %s has been edited by %s. The new frequency of contribution is %.', 'contribution_edit');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (173, '2021-10-13 12:35:42.000000', false, 'English', 'Dear %s, %s has applied for a loan of Tsh. %s in group %s. Kindly login to Vicoba to approve.', 'loan_applied');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (172, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Karibu %s, timiza malengo yako ya kifedha -weka akiba, kopesha, wekeza na ukue..', 'loan_applied');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (133, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s imefanya malipo ya adhabu ya Tsh. %s kwa kikundi %s.', 'withdrawal_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (131, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s amekataa kuondoka kwa %s kutoka kwa kikundi %s.', 'loan_repayment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (120, '2021-10-13 13:48:25.000000', false, 'Kiswahili', '%s, imefanya marejesho ya mkopo kwa kikundi %s ya Tsh. %s.', 'guarantor_decline_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (127, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s, imekataa kudhamini %s kwa maombi yao ya mkopo ya Tsh. %s', 'loan_disburse');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (135, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Tumia %s kuunda nenosiri lako kwa Programu ya Chama', 'penalty_created');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (165, '2021-10-13 12:35:42.000000', false, 'Kiswahili', '%s amewasha bidhaa ya mkopo %s kwa kikundi %s.', 'loan_product_deactivated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (134, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Kikundi chako %s kimezimwa. Hakuna miamala itakayoruhusiwa.', 'outsanding_contribution_payment');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (144, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Weka upya Nenosiri la Vicoba Barua pepe', 'penalty_payment_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (156, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Karibu %s, timiza malengo yako ya kifedha -weka akiba, kopesha, wekeza na ukue..', 'member_withdraw_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (139, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Mchango %s wa kikundi %s umehaririwa na %s. Mzunguko mpya wa mchango ni%.', 'request_to_leave_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (136, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Umealikwa kwa %s. Pakua Vicoba app kwenye Google Playstore au iOS Appstore ili kuingia/kujisajili na kukubali mwaliko.', 'penalty_created_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (167, '2021-10-13 12:35:42.000000', false, 'Kiswahili', '%s amezima bidhaa ya mkopo %s kwa kikundi %s.', 'contribution_updated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (132, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s ameidhinisha kuondoka kwa %s kutoka kwa kikundi %s.', 'loan_repayment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (126, '2021-10-13 12:35:42.000000', false, 'Kiswahili', '%s, imekubali kudhamini %s kwa maombi yao ya mkopo ya Tsh. %s', 'contribution_payment_success_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (174, null, false, null, '%s amehariri mchango %s wa kikundi %s. Kiasi kipya ni Tsh. %s itachangiwa kila %s.', null);
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (158, '2021-10-13 15:39:39.000000', false, 'English', '%s has created loan product %s for group %s.', 'loan_product_created');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (159, '2021-10-13 15:39:39.000000', false, 'English', '%s has updated loan product %s for group %s. The new maximum mount is Tsh. %s and the new minimum is Tsh. %s with a user saving percentage of %s and penalty value of %s.', 'loan_product_updated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (111, '2021-10-14 11:00:05.000000', false, 'Kiswahili', 'Mpendwa %s, mdhamini wako %s kwa ombi lako la mkopo wa Tsh %s amekubali ombi la udhamini.', 'first_time_login');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (110, '2021-10-14 09:57:12.000000', false, 'Kiswahili', 'Mpendwa %s , mkopo wako wa Tsh %s umeidhinishwa. Mkopo utatolewa kwa akaunti yako.', 'device_verification');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (104, '2021-03-26 14:19:06.000000', false, 'Kiswahili', 'Mpendwa %s, malipo ya mchango wako wa kikundi ya Tsh %s, yamepokelewa.', 'newmember_inviteemail');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (115, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Ndugu Mwanachama, %s imekuomba uwe mdhamini wa maombi ya mkopo ya Tsh %s. Tafadhali ingia kwenye Chama24 ili kukubali au kukataa.', 'contribution_payment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (100, '2020-04-16 10:59:01.000000', false, 'Kiswahili', '<#> Mpendwa %s, tumia %s kuthibitisha kifaa chako. %s', 'resetemail_body');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (101, '2020-04-16 10:59:01.000000', false, 'Kiswahili', '<#> Mpendwa %s, tumia %s kama kipini chako ili kuingia kwenye programu ya Chama. %s', 'otpsms');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (103, '2020-04-16 10:59:01.000000', false, 'Kiswahili', 'Mpendwa %s, kulikuwa na hitilafu wakati wa kuhamisha %s hadi kwenye akaunti yako ya Mpesa. Tafadhali jaribu tena baadae.', 'fullstatementemail_body');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (160, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Arifa ya Kujiondoa', 'loan_product_created');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (106, '2021-04-15 11:31:53.000000', false, 'Kiswahili', 'Mpendwa %s, malipo ya mchango wako wa kikundi ya Tsh %s, hayakuweza kukamilika.', 'withdrawal_notification_subject');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (108, '2021-10-13 15:06:47.000000', false, 'Kiswahili', 'Mpendwa %s, malipo yako ya adhabu ya Tsh %s hayakukamilika.', 'leave_group_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (114, '2021-10-19 23:10:55.000000', false, 'Kiswahili', '%s ametoa mchango wa Tsh. %s kwa kikundi %s.', 'resetemail_subject');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (161, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Bofya kwenye kiungo kilichotolewa ili kuwezesha akaunti yako na kuingia', 'loan_product_updated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (99, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kuondoka kwenye kikundi %s limekataliwa. Tafadhali wasiliana na usimamizi/kamati ya kikundi.', 'group_enabled');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (98, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kuondoka kwenye kikundi %s limeidhinishwa. Wewe si mwanachama tena wa kikundi hiki.', 'group_disabled');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (105, '2021-03-26 14:20:13.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kujitoa la Tsh %s limeidhinishwa. Pesa zitatumwa kwa akaunti yako.', 'newmember_welcomeemail');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (113, '2021-10-19 23:10:55.000000', false, 'Kiswahili', '%s amechaguliwa kama %s mpya ya kikundi %s.', 'newmember_invitesms');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (109, '2021-10-13 15:20:44.000000', false, 'Kiswahili', 'Mpendwa %s, mdhamini wako %s kwa ombi lako la mkopo wa Tsh %s amekataa ombi la udhamini.', 'leave_group_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (107, '2021-06-22 10:42:39.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kuondolewa la Tsh %s limekataliwa. Tafadhali wasiliana na wasimamizi wa kikundi.', 'new_account_activation_email');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (112, '2021-10-19 23:10:55.000000', false, 'Kiswahili', 'Mpendwa %s , mkopo wako wa Tsh %s umekataliwa. Tafadhali wasiliana na wasimamizi wa kikundi.', 'b2c_error');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (175, '2022-09-05 07:51:13.270000', false, 'Kiswahili', 'Karibu', 'welcome_template');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (7, '2020-04-16 10:59:01.000000', false, 'English', 'You''ve been invited to %s.Kindly login/signup to Chama24 to accept the invitation.', 'existingmember_invitesms');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (1, '2020-04-16 10:59:01.000000', false, 'English', 'Vicoba Password Reset Email', 'resetemail_subject');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (3, '2020-04-16 10:59:01.000000', false, 'English', 'Follow the link to activate your account', 'resetemail_body');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (163, '2021-10-13 12:35:42.000000', false, 'English', '%s has activated the loan product %s for group %s.  ', 'loan_product_activated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (164, '2021-10-13 12:35:42.000000', false, 'English', '%s has deactivated the loan product %s for group %s.', 'loan_product_deactivated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (119, '2021-10-13 11:57:34.000000', false, 'Kiswahili', 'Mpendwa %s, una %s mchango ujao wa mchango %s wa Tsh. %s.', 'penalty_payment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (166, '2021-10-13 12:35:42.000000', false, 'English', '%s has edited the contribution %s for group %s. The new amount is Tsh. %s to be contributed every %s.', 'contribution_updated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (124, '2021-10-13 13:37:57.000000', false, 'Kiswahili', 'Mpendwa %s, umeadhibiwa Tsh. %s kwa kikundi %s rejeleo la mchango. nambari %s. Piga *150*85# kulipa.', 'guarantor_request');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (117, '2021-10-13 12:27:03.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kuondoka %s limekataliwa na %s.', 'contribution_payment_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (129, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Mpendwa %s, malipo yako ya adhabu ya Tsh %s yamekamilika.', 'withdrawal_failure');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (142, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s amesasisha bidhaa ya mkopo %s kwa kikundi %s. Kiwango kipya cha juu zaidi cha kupanda ni Tsh. %s na kima cha chini kipya ni Tsh. %s yenye asilimia ya kuokoa ya mtumiaji ya %s na thamani ya adhabu ya %s.', 'request_to_leave_decline_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (162, '2021-10-13 12:35:42.000000', false, 'Kiswahili', 'Fuata kiungo ili kuwezesha akaunti yako', 'loan_product_activated');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (118, '2021-10-20 11:30:05.000000', false, 'Kiswahili', 'Mpendwa %s, uondoaji wako wa Tsh. %s kutoka kundi %s haikufaulu.', 'withdrawal_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (130, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s, imetoa Tsh. %s kutoka kwa kikundi %s.', 'contribution_payment_reminder');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (116, '2021-10-20 11:28:12.000000', false, 'Kiswahili', 'Mpendwa %s , mkopo wako wa Tsh. %s , imetolewa.', 'withdrawal_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (138, '2021-10-13 15:39:39.000000', false, 'Kiswahili', '%s ameomba kutoa Tsh. %s kutoka kwa kikundi %s.', 'guarantor_decline_request_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (128, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Mpendwa %s, ombi lako la kuondoka %s limeidhinishwa na %s.', 'request_to_leave_decline');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (123, '2021-10-13 15:54:42.000000', false, 'Kiswahili', 'Mpendwa %s, malipo yako ya mchango ambayo bado hayajalipwa ya Tsh. %s imelipwa kwa kikundi %s ref. %s. Salio jipya la michango iliyobaki ni Tsh %s.', 'loan_declined');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (143, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Umealikwa kwa %s. Tafadhali ingia/ ujiandikishe kwa Chama24 ili kukubali mwaliko.', 'request_to_leave_approve_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (121, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Mpendwa %s, marejesho ya mkopo wako wa Tsh. %s kwa kikundi %s haikufaulu.', 'loan_approved');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (140, '2021-10-13 11:57:34.000000', false, 'Kiswahili', 'Mpendwa %s, %s ameomba mkopo wa Tsh. %s katika kikundi %s. Tafadhali ingia kwenye Vicoba ili kuidhinisha.', 'penalty_payment_success');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (137, '2021-10-13 15:39:39.000000', false, 'Kiswahili', 'Kikundi chako %s kimewashwa na sasa kiko tayari kuruhusu miamala.', 'guarantor_accept_request_group');
insert into public.message_templates (id, created_on, soft_delete, language, template, type) values (176, '2022-09-06 08:56:50.728000', false, 'English', 'Member Withdraw', 'Member_withdrawal');
--Add Roles Data
INSERT INTO public.rolesconfig (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name, resourceid, rules) VALUES (4, 'ADMIN', '2022-06-16 16:46:54.000000', 'ADMIN', '2022-06-16 16:47:21.000000', false, 'ROLE_PORTAL_USER', 'esb_5_1', '{"reports":["cancreate","canview","candelete","canedit"]}');
INSERT INTO public.rolesconfig (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name, resourceid, rules) VALUES (1, 'ADMIN', '2022-06-16 16:46:48.000000', 'ADMIN', '2022-06-16 16:47:15.000000', false, 'ROLE_ADMIN', 'finmanager', '{"reports":["cancreate","canview","candelete","canedit"]}');
INSERT INTO public.rolesconfig (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name, resourceid, rules) VALUES (3, 'ADMIN', '2022-06-16 16:46:52.000000', 'ADMIN', '2022-06-16 16:47:20.000000', false, 'ROLE_USER', 'chama_clientid', '{"reports":["cancreate","canview","candelete","canedit"]}');
INSERT INTO public.rolesconfig (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name, resourceid, rules) VALUES (2, 'ADMIN', '2022-06-16 16:46:50.000000', 'ADMIN', '2022-06-16 16:47:19.000000', false, 'ROLE_PORTAL_USER', 'chama_portal', '{"reports":["cancreate","canview","candelete","canedit"]}');

-- Add Schedule Types Data
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (1, null, '2020-03-23 14:53:03.000000', null, null, false, 'weekly');
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (2, null, '2020-03-23 14:53:09.000000', null, null, false, 'daily');
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (3, null, '2020-03-23 14:53:16.000000', null, null, false, 'monthly');
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (4, null, '2020-03-23 14:53:28.000000', null, null, false, 'annualy');
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (5, null, '2021-03-29 08:56:07.000000', null, null, false, 'bi-weekly');
INSERT INTO public.schedule_types_tbl (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, name) VALUES (6, null, '2021-04-15 12:07:04.000000', null, null, false, 'quarterly');
-- Add Transaction Types Data
INSERT INTO public.transaction_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, transaction_type) VALUES (1, null, '2020-01-31 13:29:25.000000', null, null, false, 'DEBIT');
INSERT INTO public.transaction_types (id, created_by, created_on, last_modified_by, last_modified_date, soft_delete, transaction_type) VALUES (2, null, '2020-01-31 13:29:25.000000', null, null, false, 'CREDIT');
